version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: superhack/server:latest
    depends_on:
        - postgresdb
    ports:
      - '8081:8081'

  postgresdb:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=superhack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
